In [3]:
import numpy as np
def homework(message):
    print("\n>>>>>", message, "\n")
temperature = [20.1, 20.1, 20.2, 20.4]
print(temperature)

t1 = temperature * 5

print(f"При множенні на 5 маємо: {t1}")
homework("Чому маємо такий результат?")

t1 = [ x*5 for x in temperature]
print(f"Тепер отримаємо: {t1}")
homework("Чому тепер множення успішне?")

t2 = np.array(temperature)
print("Масив з використанням методів NumPy", t2)

t3 = t2 * 5
print("При множенні на 5 отримуємо:", t3)

start = 5
size_of_vec = 100
x = range(size_of_vec)
a = np.arange(size_of_vec)
print(f"Масив згенерований простим range: {x[0:5]} та методом arange: {a[0:5]}")
homework("Виведіть весь діапазон чисел.")
print(a, "\n")

a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")
homework("Виведіть останній діапазон в згенерованому масиві.")
print(a, "\n")

x = range(start, size_of_vec)
print("Те саме але з вбудованою функцією range:", x)
print("Власне вивід значень:", list(x)[0], )
homework("Виведіть якесь число з середини діапазону.")
print(a[42], "\n")

# дробові числа
x = np.arange(10.4)
print("Будем мати:", x)
# крок
x = np.arange(0.5, 4, 0.5)
print("З кроком 0.5:", x)
# Заокруглення
x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x, "\n Зерніть уагу на заокруглення")
homework("Згенеруйте значення де крок буде мати чотири нулі після коми, яким буде результат?")
x = np.arange(0.0, 0.0001, 0.00002)
print(x, "\n")
y = x * 2.5
print("Після перемноження:", y)
homework("Піднесіть отримане число до степеня та поділіть на 0.4 - Яким буде результат?")
y = y*y/0.4
print(y, "\n")

examples = {
    '5 рядків': np.array([[1], [2], [3], [4], [5]]),
    '5 стовпців': np.array([[1, 2, 3, 4, 5]]),
    '5 елементів': np.array([[[1, 2, 3, 4, 5]]])
    }
for a in examples:
    print(f"Для {a} маємо shape: \n{examples[a].shape} \nта вигляд: \n{examples[a]}")

homework(f"Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів.")

homewk = np.array([[1, 2, 3], [4, 5 ,6], [7, 8, 9]])
print(homewk, "\n shape - " ,homewk.shape)

F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
print(f"""Масив: {F}
Виміри: {F.shape}
Памятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:\n {F[0]}
Другий:\n {F[1]}
Останній, {len(F)}: \n {F[7]}""")

print(f"""Можемо скористатись відємними індексами якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:\n {F[-1]}
Передостанній:\n {F[-2]}""")

homework("Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами.")
print(F[1], F[3], F[-4], F[-1])

A = np.array([ [3.4, 8.7, 9.9],
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8],
               [7.0, -3.9, 5.1]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: {A[0]}
    Останній рядок: {A[-1]}
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи):
    Перший стовпець: {A[:,0]}
    Останній стовпець: {A[:,-1]}
Потрібно задавати два значення для отримання конкретного елемента:
    Перший елемент: {A[0][0]} або {A[0, 0]}
    Останній елемент: {A[3][2]} або {A[-1][-1]} або {A[3, -1]}
""")
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(f"""Масив:
{S}
Виміри: {S.shape}
Беремо декілька елементів: {S[2:5]}
Всі елементи до заданого: {S[:4]}
Всі елементи від заданого до кінця: {S[6:]}
Всі елементи: {S[:]}
""")
homework("Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву.")
print(S[-4:])

A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо декілька рядків:
{A[0:2]}
Два перші стовпці:
{A[:, 0:2]}
Два останні рядки:
{A[3:, :]}
Беремо підматрицю (нижні елементи):
{A[-3:, -3:]}
""")
homework("Попрактикуйтесь у витягуванні елементів, візьміть матрицю 2х2 з нижнього та верхнього кутка матриці А.")
print(A[-2:, 0:2], "\n", A[0:2, -2:])

A = np.arange(28).reshape(4, 7)

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо кожен дугий елемент першого рядка:
{A[0, ::2]}
Беремо кожен третій елемент першого рядка:
{A[0, ::3]}
Кожен другий елемент в кожномуу другому рядку:
{A[::2, ::2]}
Останні три елементи в кожному другому рядку:
{A[::2, 4:]}
Можна повнісню змінити порядок елементів (дзерально обернемо):
{A[::-1, ::-1]}
""")

homework("Попрактикуйтесь у витягуванні елементів, будь-яка робоча комбінація.")
print(A[1:3, 3:7])

A = np.arange(50)
all_even = (A%2==0) # парні
complex = (A<30) & (A/5<2)

print(f"""Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або {all_even[0]} для {A[0]} або {all_even[1]} для {A[1]}.
Після підставляння умови пошуку парних чисел в масив отримаємо:
{A[all_even]}
Або застосувавти більш комплексну умову з двох порінянь:
{A[complex]}""")

homework("Виведіть всі непарні числа з даного масиву.")
A_odd = (A%2==1)
print(A[A_odd])



homework("Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементів які належать діагоналі.")
print(A[1][1], A[-1][-1], A[0,-2])
A = np.arange(40).reshape(4, 10)
x = np.array([1, 3])
print(A,x)
A *= 5
x += 1
B = A[2:4, -4:]
x = x.reshape(2, 1)
print(A, "\n", x)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]] [1 3]
[[  0   5  10  15  20  25  30  35  40  45]
 [ 50  55  60  65  70  75  80  85  90  95]
 [100 105 110 115 120 125 130 135 140 145]
 [150 155 160 165 170 175 180 185 190 195]] 
 [[2]
 [4]]
